spring:
  datasource:
    url: jdbc:h2:mem:user
    username: user
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8083