version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: wertwsat1
      POSTGRES_DB: taskmanager



